import Login from "@/components/Login";
import UserDashboard from "@/components/UserDashboard";
import { useAuth } from "@/context/AuthContext";
import Head from "next/head";

export default function Home() {

  const { currentUser } = useAuth()
  console.log(currentUser)

  return (
    <>
      <Head>
        <title>Create Next APP</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      {!currentUser && <Login/>}
      {currentUser && <UserDashboard/>}
    </> 
  )
}
